<?php

		// Exit if accessed directly
		if ( ! defined( 'ABSPATH' ) ) {
			exit;
		}

		function fusion_builder_add_photography_demo( $demos ) {

		$demos['photography'] = array (
  'category' => 'Avada Photography',
  'pages' => 
  array (
     
    array (
      'name' => 'Photography Home',
      'link' => 'https://avada.theme-fusion.com/photography/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="40px" padding_bottom="2.5%" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_small="20px"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="3" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]CAPTURING MOMENTS AS THEY HAPPEN[/fusion_title][fusion_text content_alignment="center" fusion_font_variant_text_font=""]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" hide_on_mobile="no" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" border_style="solid" padding_top="0px" padding_right="4%" padding_bottom="100px" padding_left="4%" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_bottom_small="60px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" background_position="left top" background_color="" border_color="" border_style="solid" spacing="yes" background_image="" background_repeat="no-repeat" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="true" hover_type="none" link="" border_position="all" align_self="flex-start" first="true"][fusion_portfolio layout="grid" picture_size="auto" text_layout="boxed" columns="4" one_column_text_position="below" column_spacing="40" portfolio_title_display="title" portfolio_text_alignment="center" filters="no" cat_slug="" exclude_cats="" number_posts="8" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="yes" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-home',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-home',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'About Me',
      'link' => 'https://avada.theme-fusion.com/photography/about-me/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="40px" padding_bottom="3%" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_small="20px" padding_right_small="20px" padding_left_small="20px"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="3" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]BORN TO SHOOT THE WORLD AROUND ME[/fusion_title][fusion_text content_alignment="center"]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#212326" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="160px" padding_bottom="100px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_top_medium="80px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_imageframe lightbox="no" gallery_id="" lightbox_image="" style_type="none" hover_type="none" bordercolor="rgba(255,255,255,.2)" bordersize="" borderradius="4px" stylecolor="" align="none" link="" linktarget="_self" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" hide_on_mobile="no" class="" id=""] <img src="https://placehold.it/1170x451" alt="" />[/fusion_imageframe][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="9%" padding_bottom="0%" padding_left="9%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="left" size="3" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]Always Searching For The Shot[/fusion_title][fusion_text]Aliquam interdum neque non quam scelerisque efficitur. Ut sagittis, mi sed vestibulum bibendum, lacus lacus vulputate enim, vel posuere diam nibh sit amet velit. Vivamus pulvinar sit amet enim sed sagittis. Ut quis porttitor lacus. Nulla tris cursus. Pellentesque molis velit eu bidum.[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="9%" padding_bottom="" padding_left="9%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%" align_content="flex-start" margin_bottom_medium="15px"][fusion_progress height="" text_position="" percentage="88" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Landscapes[/fusion_progress][fusion_progress height="" text_position="" percentage="93" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Wildlife[/fusion_progress][fusion_progress height="" text_position="" percentage="98" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Business[/fusion_progress][fusion_progress height="" text_position="" percentage="84" show_percentage="" unit="" filledcolor="" filledbordercolor="" filledbordersize="" unfilledcolor="" striped="no" animated_stripes="no" textcolor="" class="" id=""]Lifestyle[/fusion_progress][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_image="https://placehold.it/2000x1287" background_parallax="up" enable_mobile="no" parallax_speed="0.4" background_repeat="no-repeat" background_position="center center" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="180px" padding_bottom="140px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_medium="100px" padding_bottom_medium="40px" padding_top_small="80px" padding_bottom_small="20px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="#dfdfdf"][fusion_testimonial name="ANSEL ADAMS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence."[/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are."[/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected."[/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#212326" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="160px" padding_bottom="40px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_medium="100px" padding_bottom_medium="0px" padding_top_small="80px" padding_bottom_small="10px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="8%" padding_bottom="0%" padding_left="8%" margin_top="" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="1" animation_offset="top-into-view" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_medium="20px" margin_bottom_small="0px"][fusion_blog number_posts="" offset="" cat_slug="" exclude_cats="" show_title="yes" title_link="yes" thumbnail="yes" excerpt="yes" excerpt_length="2" meta_all="no" meta_author="yes" meta_categories="yes" meta_comments="yes" meta_date="yes" meta_link="yes" meta_tags="yes" scrolling="pagination" strip_html="yes" blog_grid_columns="3" blog_grid_column_spacing="40" layout="medium" class="" id="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="100" padding_bottom="0" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="0px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="3" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]
<p>CLIENTS I\'VE WORKED WITH</p>
[/fusion_title][fusion_images picture_size="auto" hover_type="none" autoplay="yes" columns="5" column_spacing="30" scroll_items="1" show_nav="no" mouse_scroll="yes" border="no" lightbox="no"][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][fusion_image link="" linktarget="_self" image="https://placehold.it/270x160" alt="" /][/fusion_images][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-about-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_portfolio_category' => 'a:1:{i:0;s:1:"0";}',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-about-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'Collections',
      'link' => 'https://avada.theme-fusion.com/photography/collections/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" margin_top_medium="80px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="https://placehold.it/1170x300" background_repeat="no-repeat" background_position="center top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="100px" padding_right="0px" padding_bottom="100px" padding_left="0px" margin_top="" margin_bottom="0px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_bottom_medium="80px" padding_top_small="30px"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="4" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="#c6c6c6" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]
<p>FRESH WORKS FROM AROUND THE WORLD</p>
[/fusion_title][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="1" font_size="55px" animated_font_size="" line_height="65px" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]
<p>THE AVADA COLLECTION</p>
[/fusion_title][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_bottom="100px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_bottom_medium="60px" padding_bottom_small="76"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_portfolio layout="grid" picture_size="auto" text_layout="boxed" columns="2" one_column_text_position="below" column_spacing="30" portfolio_title_display="title" portfolio_text_alignment="center" filters="no" cat_slug="" exclude_cats="" number_posts="8" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="no" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center bottom" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="120px" padding_bottom="80px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_bottom_small="20px" padding_top_small="80px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="#dfdfdf"][fusion_testimonial name="ANSEL ADAMS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence." [/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are." [/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" image="" image_border_radius="" company="" link="" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected." [/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => '',
        'pyre_slider_position' => 'default',
        'pyre_slider_type' => 'no',
        'pyre_slider' => '0',
        'pyre_wooslider' => '0',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_fallback' => '',
        'pyre_avada_rev_styles' => 'default',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg' => '',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg' => '',
        'pyre_page_bg_color' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg' => 'https://placehold.it/2340x1200',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'no-repeat',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_page_title' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
      ),
    ),
     
    array (
      'name' => 'Hire Me',
      'link' => 'https://avada.theme-fusion.com/photography/hire-me/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="20px" padding_bottom="80px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" flex_justify_content="center" padding_right_medium="8%" padding_left_medium="8%" padding_top_small="50px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="10%" padding_bottom="0%" padding_left="10%" margin_top="" margin_bottom="30px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_left_medium="20px" padding_right_medium="20px" margin_bottom_medium="30px"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" before_text="" rotation_text="" highlight_text="" after_text="" content_align_medium="" content_align_small="" content_align="center" size="3" font_size="" animated_font_size="" line_height="" letter_spacing="" dimensions_medium="" dimensions_small="" text_color="" animated_text_color="" highlight_color="" style_type="none" sep_color="" animation_type="" animation_direction="left" animation_speed="0.3" animation_offset="" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" class="" id="" fusion_font_variant_title_font=""]LOOKING FOR BEAUTIFUL IMAGES THAT CAPTURE THE OCCASION?[/fusion_title][fusion_text]
<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqui.</p>
[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="false" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%"][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="0" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_right="2%" spacing_left="2%"][fusion_form form_post_id="1040" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" /][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="true" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%"][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" hide_on_mobile="no" background_color="#25272a" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" border_style="solid" padding_top="80px" padding_right="4%" padding_bottom="100px" padding_left="4%" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" flex_justify_content="center" padding_bottom_small="70px"][fusion_builder_row][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="false" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%"][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_right="2%" spacing_left="2%"][fusion_title size="3" content_align="center" style_type="single solid" sep_color="" margin_top="" margin_bottom="" class="" id="" fusion_font_variant_title_font=""]MORE FROM THE AVADA COLLECTION[/fusion_title][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="true" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" element_content="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%"][/fusion_builder_column][fusion_builder_column type="1_1" type="1_1" layout="1_1" background_position="left top" background_color="" border_color="" border_style="solid" spacing="yes" background_image="" background_repeat="no-repeat" padding_top="" padding_right="" padding_bottom="" padding_left="" margin_top="0px" margin_bottom="0px" class="" id="" animation_type="" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="true" hover_type="none" link="" border_position="all" align_self="flex-start" first="true"][fusion_portfolio layout="grid" picture_size="auto" text_layout="boxed" columns="5" one_column_text_position="below" column_spacing="40" portfolio_title_display="title" portfolio_text_alignment="center" filters="no" cat_slug="" exclude_cats="" number_posts="5" pagination_type="none" offset="" content_length="excerpt" excerpt_length="0" strip_html="yes" carousel_layout="title_on_rollover" scroll_items="" autoplay="no" show_nav="yes" mouse_scroll="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" animation_type="" animation_direction="down" animation_speed="0.1" animation_offset="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-hire-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-hire-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'On Location',
      'link' => 'https://avada.theme-fusion.com/photography/on-location/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="50px" padding_bottom="20px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_top_small="30px" padding_bottom_small="0px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="12%" padding_bottom="0%" padding_left="12%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_right_medium="6%" padding_left_medium="6%" padding_right_small="20px" padding_left_small="20px" margin_bottom_small="0px"][fusion_blog number_posts="" offset="" cat_slug="" exclude_cats="" show_title="yes" title_link="yes" thumbnail="yes" excerpt="yes" excerpt_length="45" meta_all="no" meta_author="yes" meta_categories="yes" meta_comments="yes" meta_date="yes" meta_link="yes" meta_tags="yes" scrolling="pagination" strip_html="yes" blog_grid_columns="3" blog_grid_column_spacing="40" layout="large" class="" id="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="#25272a" background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center center" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="100px" padding_bottom="40px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_small="70px" padding_bottom_small="10px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_color="" background_image="" background_repeat="no-repeat" background_position="left top" hover_type="none" link="" border_position="all" border_color="" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" margin_top="" margin_bottom="" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="" class="" id="" min_height="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true"][fusion_title size="3" content_align="center" style_type="none" sep_color="" margin_top="" margin_bottom="36px" class="" id="" fusion_font_variant_title_font=""]SUBSCRIBE TO FOLLOW US ON LOCATION[/fusion_title][fusion_form form_post_id="1044" hide_on_mobile="small-visibility,medium-visibility,large-visibility" class="" id="" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-on-location',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-on-location',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
  ),
);

			return $demos;
		}
		add_filter( 'fusion_builder_get_demo_pages', 'fusion_builder_add_photography_demo' );